# Generated by Django 5.2.15 on 2026-06-18 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('egress_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meetings.meeting')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_recordings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['egress_id'], name='meeting_rec_egress__99baba_idx')],
            },
        ),
    ]
