# Generated by Django 5.2.15 on 2026-06-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='has_spoken',
            field=models.BooleanField(default=False),
        ),
    ]
