# Generated by Django 5.2.15 on 2026-06-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingparticipant_has_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='camera_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
